name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

  deploy_android:
    name: Deploy to Google Play
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Add steps to build the Android app (.apk or .aab)
      # Use fastlane to deploy to Google Play Store

  deploy_ios:
    name: Deploy to App Store
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Add steps to build the iOS app
      # Use fastlane to deploy to Apple App Store
